### ISSUE TITLE
Missing Features from Fabric Version

### ISSUE THREAD

**Issue by Someone-Else-Was-Taken** [Someone-Else-Was-Taken/BetterEndForge-Reforked#1]
Here, I'm looking for help finding the features that are currently missing from the fabric version of BetterEnd.

I have decided against a full rewrite of the mod due to BcLib not existing on forge, and as such that brings a new issue. Currently Beethoven's build isn't in code parity with the fabric version. Meaning I have no way of knowing what is missing without going through every single feature of both versions in game.

Please reply to this with any features that are missing, it would help out a ton in speeding up progress.

Known:
- ~~Umbral Valley Biome~~ Added in 2.0
- Cave Gen

**Comment by SethbotStar** [comment]
Missing block tags #38
Chorus Flower Missing Model Change #39

**Comment by MagmaSlime123** [comment]
> > yoyoyoyo really dig the mod port btw. a couple things that i've noticed so far using the mod however. one of which is the lack of mod compatibility with the smelter; the betterend discord states that "Coal blocks, charcoal blocks, blaze rods, lava and mod fuel with 2000+ ticks of burning" are able to be used in the smelter, while in the port only coal blocks, blaze rods, and lava work. Charcoal blocks have yet to be implemented in the port as well, which would be a really helpful thing. I just talked with paulevs, they said that charcoal blocks were added in 0.9.0
> 
> I didn't even know those were a feature. Although, while I had intended to add the smaller features in after 2.0. I'll add Charcoal Blocks in early for you.

Re-start development or remove this mod. It's been dead for 2 years with no info as to why.
