### ISSUE TITLE
Crash while generating biome on the server

### ISSUE THREAD

**Issue by SSKirillSS** [Someone-Else-Was-Taken/BetterEndForge-Reforked#20]
Server just crashes when generating umbra valley biome.

Mod version: betterendforge-1.16.5-2.3
Crash-report: https://pastebin.com/6q0CW24S

**Comment by SSKirillSS** [comment]
36.2.8 for now.

And yea, there are some mods. But check log, there is nothing about other mods

**Comment by Schummel8** [comment]
On line 58 it says something with serene seasons.
Does it also crashes if you only have this mod and try to enter the biome?
Also that is not the log, that's the crash report, but the debug.log would also be helpful.

**Comment by SSKirillSS** [comment]
It will say whatever actually possible to say if something was injected into the related methods. Root of issue source in most cases will be defined in the first line of the stacktrace. In this case it was missed method from the Vector3f class. afaik Vector stuff common-sided, so it should exist both on client and server, but used in my case mapped method exists only on the client side:
![image](https://user-images.githubusercontent.com/38190325/139495000-d519d5ca-43d7-4919-826a-b8c7dbfa94c6.png)

So fix should be somewhere here: https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/blob/master/src/main/java/mod/beethoven92/betterendforge/common/world/feature/ThinArchFeature.java#L74

**Comment by SSKirillSS** [comment]
Still an issue with 2.3.2 release which should fix this bug: https://pastebin.com/6i4jgMMR

**Comment by MoonMoonShark** [comment]
so, @SSKirillSS does it seem to be just the umbra valley? if i deactivate that biome until this is fixed, does that seem to at least stave off the crashes for now?

**Comment by SSKirillSS** [comment]
Seems like issue appears only while generating thin arch feature (which is umbra valley thing). So "no umbra valley = no crash" before mod dev will fix it. But bug is rly easy to fix, seems like mod dev just busy now.

**Comment by SSKirillSS** [comment]
@Someone-Else-Was-Taken, tried to reproduce this issue with the latest BER version (2.4 for now), and this crash stiil seems like an issue. New log: https://pastebin.com/pT86TrTq
