### ISSUE TITLE
[Bug] mobs spawning in light level over 7

### ISSUE THREAD

**Issue by Torben8** [Someone-Else-Was-Taken/BetterEndForge-Reforked#21]
When playing with this mod it seems that hostile mobs can spawn on blocks with light level over 7.
So far i believe 11 is the highest light level i have seen mobs spawn.
I only used this mod, version 2.3 on forge 36.2.4

Screenshot (zombie spawned in light level 11)
![2021-10-29_17 55 05](https://user-images.githubusercontent.com/79870893/139466085-943a78fe-261a-47dc-8085-f2b4da3b5843.png)

**Comment by Someone-Else-Was-Taken** [comment]
Are you running with any other mods?

**Comment by Schummel8** [comment]
No, as stated above this was the only mod to make sure it was not a compat problem.

**Comment by Someone-Else-Was-Taken** [comment]
Sorry, missed that part.
I'll look into it.
