### ISSUE TITLE
"Can't find attribute betterendforge:blindness_resistance" crash

### ISSUE THREAD

**Issue by Reshirou** [Someone-Else-Was-Taken/BetterEndForge-Reforked#22]
Here's log:
https://pastebin.com/scVwE7Xk

I am testing with Magnesium, I will test without it as well

**Comment by Reshirou** [comment]
Still crashes without Magnesium

**Comment by AlienXtream** [comment]
getting this too on "abyssaldepths:body_part"

[crash-2021-10-31_21.08.45-server.txt](https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/files/7448510/crash-2021-10-31_21.08.45-server.txt)

**Comment by netcore10** [comment]
Same here, aswell as for abyss 2

**Comment by Thombias** [comment]
I'm just got this crash as well but i don't have Endergetic Expansion, Abyssal Depths or Abyss 2 in my modpack. I run completely different mods and just randomly crashed while flying through the overworld.
[crash-2021-11-07_12.58.00-server.txt](https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/files/7492199/crash-2021-11-07_12.58.00-server.txt)
