### ISSUE TITLE
Crash during removeBlindness event

### ISSUE THREAD

**Issue by Phweeeee** [Someone-Else-Was-Taken/BetterEndForge-Reforked#24]
[debug.log](https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/files/7448941/debug.log)
[latest.log](https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/files/7448942/latest.log)

This occurs on BEFR 2.3.1.

**Comment by SSKirillSS** [comment]
Duplicate of https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/22

**Comment by KentaTheButcher** [comment]
Is this bug getting solved?
Still happening in the last updates
