### ISSUE TITLE
"CREATURE" entities are not allowed to spawn, at all

### ISSUE THREAD

**Issue by Carro1001** [Someone-Else-Was-Taken/BetterEndForge-Reforked#29]
I've recently discovered that any mob set as "creature" doesn't seem to spawn in any biome with this mod installed, which includes:

Booflos
Puffbugs (though their nests spawn with them inside)
Endergrades
Enderiophages

booflos don't even spawn in their own biomes, though when i tried using the older version on curseforge (before having to make the new page), things spawned just fine, without adjusting any config, and the more i looked into it, the more i noticed how all these mobs are set as "CREATURE" type entities, and none of the biomes from this mod seem to have that type of mob as a spawn option

**Comment by mosharky** [comment]
Those mobs needs extra configuration on your end for them to spawn in the end. Pretty sure Booflos and Puffbugs are only supposed to spawn in the Endergetic Expansions' biome.

**Comment by Carro1001** [comment]
I did that, and the endergetic mobs werent even spawning in their own biome until i removed/downgraded betterend

**Comment by mosharky** [comment]
you're right actually, my bad

**Comment by MagmaSlime123** [comment]
This mod is dead. Don't bother opening issues here.

**Comment by Carro1001** [comment]
sir you're 2 years late

**Comment by MagmaSlime123** [comment]
> sir you're 2 years late

I know. Not my fault.

**Comment by mosharky** [comment]
i don't understand the anger required to comment on years old issues to tell us "This mod is dead. Don't bother opening issues here". What do you think that'll produce?
