### ISSUE TITLE
crashloop

### ISSUE THREAD

**Issue by Reshirou** [Someone-Else-Was-Taken/BetterEndForge-Reforked#30]
was pregenning world with Chunky and consistently ran into crashloops that bricked the worlds. Here is a crash report

https://pastebin.com/ScCyLwMK

already reported to Chunky Pregenerator, wasnt on their end

**Comment by SSKirillSS** [comment]
Duplicate of https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/20

You can disable umbra valley biome in the config to prevent crashing
