### ISSUE TITLE
Is there compatibility with the end cities for "better end" data pack?

### ISSUE THREAD

**Issue by Scapulaunit12** [Someone-Else-Was-Taken/BetterEndForge-Reforked#35]
I was just wondering if there was compatibility with this datapack? https://www.planetminecraft.com/data-pack/end-city-for-better-end-forge-port/

**Comment by mosharky** [comment]
it should be, since all that datapack relies on is the correct modid i believe (betterendforge)

**Comment by Scapulaunit12** [comment]
I just tested it, it works
